/**
 * Die Rezeptbibliothek von Better Fit: geprueft, mit genauen Mengen, ohne
 * Naehrwerte — die rechnet der Dienst aus den Zutaten (`recipes.js`).
 *
 * Jede Zutat nennt einen Suchbegriff (`term`) und den Datensatz des
 * Mock-Katalogs (`food`). Gibt es die Schweizer Datenbank, wird ueber den
 * Begriff zugeordnet; sonst gilt der Mock-Datensatz.
 *
 * `basic`: Grundzutaten wie Salz, Oel oder Backpulver. Sie werden nie still
 * vorausgesetzt — fehlen sie im Vorrat, stehen sie als fehlend da, nur markiert.
 * `alternatives`: Ersatz bei Allergie oder Ernaehrungsform, immer gekennzeichnet.
 * Texte der Anleitung sind Inhalt (Deutsch), keine Oberflaeche.
 */

const item = (term, food, amount, unit, extra = {}) => ({ term, food, amount, unit, ...extra });

const LIBRARY = [
  {
    id: 'lib:banana-bread',
    title: 'Bananenkuchen',
    servings: 8,
    slots: ['snack', 'breakfast'],
    timeMinutes: 70,
    // Davon 50 Minuten im Ofen — selbst am Herd stehen nur 20.
    activeMinutes: 20,
    difficulty: 'easy',
    equipment: ['oven'],
    cost: 'low',
    tags: ['backen', 'resteverwertung'],
    items: [
      item('Banane', 'banana', 3, 'piece'),
      item('Weissmehl', 'flour', 250, 'g'),
      item('Ei', 'egg', 2, 'piece'),
      item('Zucker', 'sugar', 80, 'g', { basic: true }),
      item('Butter', 'butter', 80, 'g', { alternatives: ['rapeseed_oil'] }),
      item('Backpulver', 'baking_powder', 10, 'g', { basic: true }),
      item('Milch', 'milk', 60, 'ml', { alternatives: ['soy_drink'] }),
    ],
    steps: [
      'Backofen auf 180 °C vorheizen, eine Cakeform einfetten.',
      'Bananen mit einer Gabel fein zerdrücken.',
      'Butter schmelzen, mit Zucker, Eiern und Milch verrühren, Bananen dazugeben.',
      'Mehl und Backpulver mischen und kurz unterheben.',
      'In die Form füllen und 50–55 Minuten backen. Stäbchenprobe machen.',
    ],
  },
  {
    id: 'lib:banana-pancakes',
    title: 'Bananen-Pancakes',
    servings: 2,
    slots: ['breakfast'],
    timeMinutes: 20,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'low',
    tags: ['schnell'],
    items: [
      item('Banane', 'banana', 2, 'piece'),
      item('Ei', 'egg', 2, 'piece'),
      item('Weissmehl', 'flour', 60, 'g'),
      item('Backpulver', 'baking_powder', 3, 'g', { basic: true }),
      item('Rapsöl', 'rapeseed_oil', 5, 'ml', { basic: true }),
    ],
    steps: [
      'Bananen zerdrücken, mit den Eiern glatt rühren.',
      'Mehl und Backpulver unterrühren, 5 Minuten quellen lassen.',
      'Wenig Öl in einer Bratpfanne erhitzen, pro Pancake 2 EL Teig hineingeben.',
      'Bei mittlerer Hitze je Seite 2 Minuten backen.',
    ],
  },
  {
    id: 'lib:porridge-banana',
    title: 'Porridge mit Banane',
    servings: 1,
    slots: ['breakfast'],
    timeMinutes: 10,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'low',
    tags: ['schnell', 'vegetarisch'],
    items: [
      item('Haferflocken', 'oats', 60, 'g'),
      item('Milch', 'milk', 250, 'ml', { alternatives: ['soy_drink'] }),
      item('Banane', 'banana', 1, 'piece'),
      item('Mandeln', 'almonds', 10, 'g', { optional: true }),
    ],
    steps: ['Haferflocken mit Milch aufkochen.', 'Unter Rühren 4 Minuten köcheln lassen.', 'Banane in Scheiben darauf, nach Wunsch gehackte Mandeln.'],
  },
  {
    id: 'lib:quark-berries',
    title: 'Quark mit Beeren',
    servings: 1,
    slots: ['breakfast', 'snack'],
    timeMinutes: 5,
    difficulty: 'easy',
    equipment: [],
    cost: 'medium',
    tags: ['schnell', 'eiweissreich'],
    items: [item('Magerquark', 'quark', 250, 'g', { alternatives: ['skyr'] }), item('Heidelbeeren', 'blueberry', 100, 'g'), item('Honig', 'honey', 10, 'g', { optional: true })],
    steps: ['Quark glatt rühren.', 'Beeren darüber, nach Wunsch mit Honig süssen.'],
  },
  {
    id: 'lib:veggie-omelette',
    title: 'Gemüse-Omelette',
    servings: 1,
    slots: ['breakfast', 'dinner'],
    timeMinutes: 15,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'low',
    tags: ['eiweissreich'],
    items: [
      item('Ei', 'egg', 3, 'piece'),
      item('Peperoni', 'bell_pepper', 0.5, 'piece'),
      item('Zwiebel', 'onion', 0.5, 'piece'),
      item('Rapsöl', 'rapeseed_oil', 5, 'ml', { basic: true }),
      item('Salz', 'salt', 1, 'pinch', { basic: true }),
    ],
    steps: ['Peperoni und Zwiebel klein schneiden und im Öl 3 Minuten andünsten.', 'Eier mit Salz verquirlen und darübergiessen.', 'Zugedeckt bei kleiner Hitze 5 Minuten stocken lassen.'],
  },
  {
    id: 'lib:rice-chicken-broccoli',
    title: 'Reis mit Poulet und Broccoli',
    servings: 2,
    slots: ['lunch', 'dinner'],
    timeMinutes: 30,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'medium',
    tags: ['eiweissreich', 'meal-prep'],
    items: [
      item('Reis', 'rice', 150, 'g'),
      item('Pouletbrust', 'chicken_breast', 300, 'g', { alternatives: ['tofu'] }),
      item('Broccoli', 'broccoli', 400, 'g'),
      item('Sojasauce', 'soy_sauce', 20, 'ml'),
      item('Rapsöl', 'rapeseed_oil', 10, 'ml', { basic: true }),
    ],
    steps: [
      'Reis nach Packungsangabe kochen.',
      'Poulet in Streifen schneiden und im Öl 6 Minuten braten.',
      'Broccoli in Röschen teilen, 4 Minuten mitbraten, mit Sojasauce ablöschen.',
      'Mit dem Reis anrichten.',
    ],
  },
  {
    id: 'lib:spaghetti-bolognese',
    title: 'Spaghetti Bolognese',
    servings: 4,
    slots: ['lunch', 'dinner'],
    timeMinutes: 40,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'medium',
    tags: ['familie', 'meal-prep'],
    items: [
      item('Spaghetti', 'pasta', 400, 'g'),
      item('Rindshackfleisch', 'beef_mince', 400, 'g', { alternatives: ['lentils'] }),
      item('Tomatensauce', 'passata', 500, 'ml'),
      item('Zwiebel', 'onion', 1, 'piece'),
      item('Karotte', 'carrot', 1, 'piece'),
      item('Olivenöl', 'olive_oil', 15, 'ml', { basic: true }),
      item('Parmesan', 'parmesan', 40, 'g', { optional: true }),
    ],
    steps: [
      'Zwiebel und Karotte fein hacken, im Öl andünsten.',
      'Hackfleisch dazugeben und krümelig braten.',
      'Tomatensauce dazu, 20 Minuten köcheln lassen.',
      'Spaghetti al dente kochen und mit der Sauce servieren, nach Wunsch Parmesan.',
    ],
  },
  {
    id: 'lib:pasta-tomato',
    title: 'Pasta mit Tomatensauce',
    servings: 2,
    slots: ['lunch', 'dinner'],
    timeMinutes: 20,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'low',
    tags: ['schnell', 'vegan'],
    items: [
      item('Teigwaren', 'pasta', 180, 'g'),
      item('Tomatensauce', 'passata', 300, 'ml'),
      item('Knoblauch', 'garlic', 1, 'piece'),
      item('Olivenöl', 'olive_oil', 10, 'ml', { basic: true }),
      item('Parmesan', 'parmesan', 20, 'g', { optional: true }),
    ],
    steps: ['Pasta kochen.', 'Knoblauch im Öl kurz anziehen, Tomatensauce dazu, 10 Minuten köcheln.', 'Pasta untermischen.'],
  },
  {
    id: 'lib:lentil-curry',
    title: 'Rotes Linsen-Curry',
    servings: 3,
    slots: ['lunch', 'dinner'],
    timeMinutes: 35,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'low',
    tags: ['vegan', 'meal-prep'],
    items: [
      item('Rote Linsen', 'lentils', 200, 'g'),
      item('Kokosmilch', 'coconut_milk', 200, 'ml'),
      item('Tomatenpüree', 'tomato_paste', 30, 'g'),
      item('Zwiebel', 'onion', 1, 'piece'),
      item('Knoblauch', 'garlic', 2, 'piece'),
      item('Gemüsebouillon', 'broth', 500, 'ml'),
      item('Reis', 'rice', 150, 'g'),
      item('Rapsöl', 'rapeseed_oil', 10, 'ml', { basic: true }),
    ],
    steps: [
      'Zwiebel und Knoblauch hacken, im Öl andünsten, Tomatenpüree kurz mitrösten.',
      'Linsen, Bouillon und Kokosmilch dazugeben, 20 Minuten köcheln.',
      'Reis kochen und dazu servieren.',
    ],
  },
  {
    id: 'lib:tofu-stirfry',
    title: 'Tofu-Gemüse-Pfanne',
    servings: 2,
    slots: ['lunch', 'dinner'],
    timeMinutes: 25,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'medium',
    tags: ['vegan', 'eiweissreich'],
    items: [
      item('Tofu', 'tofu', 300, 'g'),
      item('Peperoni', 'bell_pepper', 1, 'piece'),
      item('Zucchetti', 'zucchini', 1, 'piece'),
      item('Sojasauce', 'soy_sauce', 30, 'ml'),
      item('Reis', 'rice', 140, 'g'),
      item('Rapsöl', 'rapeseed_oil', 15, 'ml', { basic: true }),
    ],
    steps: ['Reis kochen.', 'Tofu würfeln und im Öl goldbraun braten.', 'Gemüse in Streifen dazu, 5 Minuten braten, mit Sojasauce ablöschen.'],
  },
  {
    id: 'lib:salmon-potatoes',
    title: 'Lachs mit Kartoffeln und Spinat',
    servings: 2,
    slots: ['dinner', 'lunch'],
    timeMinutes: 35,
    activeMinutes: 15,
    difficulty: 'medium',
    equipment: ['oven', 'stove'],
    cost: 'high',
    tags: ['eiweissreich'],
    items: [
      item('Lachs', 'salmon', 250, 'g'),
      item('Kartoffel', 'potato', 500, 'g'),
      item('Spinat', 'spinach', 200, 'g'),
      item('Olivenöl', 'olive_oil', 15, 'ml', { basic: true }),
      item('Zitrone', 'lemon', 0.5, 'piece', { optional: true }),
    ],
    steps: [
      'Kartoffeln vierteln, mit der Hälfte des Öls im Ofen bei 200 °C 25 Minuten backen.',
      'Lachs die letzten 12 Minuten dazulegen.',
      'Spinat im restlichen Öl zusammenfallen lassen, mit Zitrone beträufeln.',
    ],
  },
  {
    id: 'lib:chickpea-salad',
    title: 'Kichererbsen-Salat',
    servings: 2,
    slots: ['lunch'],
    timeMinutes: 15,
    difficulty: 'easy',
    equipment: [],
    cost: 'low',
    tags: ['vegan', 'schnell', 'meal-prep'],
    items: [
      item('Kichererbsen', 'chickpeas', 300, 'g'),
      item('Gurke', 'cucumber', 0.5, 'piece'),
      item('Tomate', 'tomato', 2, 'piece'),
      item('Zwiebel', 'onion', 0.5, 'piece'),
      item('Olivenöl', 'olive_oil', 15, 'ml', { basic: true }),
      item('Zitrone', 'lemon', 0.5, 'piece'),
      item('Feta', 'feta', 60, 'g', { optional: true }),
    ],
    steps: ['Gemüse würfeln.', 'Mit abgetropften Kichererbsen mischen.', 'Mit Öl und Zitronensaft anmachen, nach Wunsch Feta darüber.'],
  },
  {
    id: 'lib:scrambled-eggs-bread',
    title: 'Rührei mit Brot',
    servings: 1,
    slots: ['breakfast'],
    timeMinutes: 10,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'low',
    tags: ['schnell', 'eiweissreich'],
    items: [item('Ei', 'egg', 3, 'piece'), item('Ruchbrot', 'bread', 2, 'piece'), item('Butter', 'butter', 5, 'g', { basic: true, alternatives: ['rapeseed_oil'] }), item('Salz', 'salt', 1, 'pinch', { basic: true })],
    steps: ['Eier mit Salz verquirlen.', 'Butter schmelzen, Eier unter Rühren langsam stocken lassen.', 'Mit dem Brot servieren.'],
  },
  {
    id: 'lib:yogurt-muesli',
    title: 'Joghurt mit Müesli und Apfel',
    servings: 1,
    slots: ['breakfast', 'snack'],
    timeMinutes: 5,
    difficulty: 'easy',
    equipment: [],
    cost: 'low',
    tags: ['schnell'],
    items: [item('Joghurt nature', 'yogurt', 180, 'g', { alternatives: ['soy_drink'] }), item('Müesli', 'muesli', 50, 'g', { alternatives: ['oats'] }), item('Apfel', 'apple', 1, 'piece')],
    steps: ['Apfel raffeln.', 'Mit Joghurt und Müesli mischen.'],
  },
  {
    id: 'lib:baked-potato-cottage',
    title: 'Ofenkartoffeln mit Hüttenkäse',
    servings: 2,
    slots: ['dinner', 'lunch'],
    timeMinutes: 45,
    activeMinutes: 10,
    difficulty: 'easy',
    equipment: ['oven'],
    cost: 'low',
    tags: ['vegetarisch'],
    items: [
      item('Kartoffel', 'potato', 600, 'g'),
      item('Hüttenkäse', 'cottage_cheese', 250, 'g'),
      item('Gurke', 'cucumber', 0.5, 'piece'),
      item('Rapsöl', 'rapeseed_oil', 10, 'ml', { basic: true }),
      item('Salz', 'salt', 2, 'pinch', { basic: true }),
    ],
    steps: ['Kartoffeln halbieren, mit Öl und Salz bei 200 °C 35 Minuten backen.', 'Gurke würfeln, mit Hüttenkäse mischen.', 'Zu den Kartoffeln servieren.'],
  },
  {
    id: 'lib:tuna-salad',
    title: 'Thon-Salat mit Mais',
    servings: 1,
    slots: ['lunch', 'dinner'],
    timeMinutes: 10,
    difficulty: 'easy',
    equipment: [],
    cost: 'low',
    tags: ['schnell', 'eiweissreich'],
    items: [
      item('Thon', 'tuna', 130, 'g'),
      item('Kopfsalat', 'lettuce', 0.25, 'piece'),
      item('Mais', 'corn', 80, 'g'),
      item('Tomate', 'tomato', 1, 'piece'),
      item('Olivenöl', 'olive_oil', 10, 'ml', { basic: true }),
      item('Ruchbrot', 'bread', 1, 'piece', { optional: true }),
    ],
    steps: ['Salat waschen und zupfen.', 'Thon, Mais und Tomate dazugeben.', 'Mit Öl anmachen.'],
  },
  {
    id: 'lib:protein-shake',
    title: 'Proteinshake mit Banane',
    servings: 1,
    slots: ['snack'],
    timeMinutes: 3,
    difficulty: 'easy',
    equipment: ['blender'],
    cost: 'medium',
    tags: ['schnell', 'eiweissreich', 'training'],
    items: [item('Molkenprotein', 'whey', 30, 'g'), item('Milch', 'milk', 300, 'ml', { alternatives: ['soy_drink'] }), item('Banane', 'banana', 1, 'piece')],
    steps: ['Alles im Mixer 20 Sekunden mixen.'],
  },
  {
    id: 'lib:tofu-scramble',
    title: 'Tofu-Rührei mit Spinat',
    servings: 1,
    slots: ['breakfast', 'dinner'],
    timeMinutes: 15,
    difficulty: 'easy',
    equipment: ['stove'],
    cost: 'low',
    tags: ['vegan', 'eiweissreich'],
    items: [
      item('Tofu', 'tofu', 200, 'g'),
      item('Spinat', 'spinach', 80, 'g'),
      item('Ruchbrot', 'bread', 1, 'piece', { optional: true }),
      item('Olivenöl', 'olive_oil', 5, 'ml', { basic: true }),
      item('Salz', 'salt', 1, 'pinch', { basic: true }),
    ],
    steps: ['Tofu mit einer Gabel zerbröseln.', 'Im Öl 5 Minuten anbraten, salzen.', 'Spinat dazugeben und zusammenfallen lassen.'],
  },
  {
    id: 'lib:soy-shake',
    title: 'Soja-Shake mit Erdnussbutter',
    servings: 1,
    slots: ['snack', 'breakfast'],
    timeMinutes: 3,
    difficulty: 'easy',
    equipment: ['blender'],
    cost: 'low',
    tags: ['vegan', 'eiweissreich', 'training'],
    items: [item('Sojadrink', 'soy_drink', 400, 'ml'), item('Erdnussbutter', 'peanut_butter', 15, 'g'), item('Banane', 'banana', 1, 'piece')],
    steps: ['Alles im Mixer 20 Sekunden mixen.'],
  },
  {
    id: 'lib:apple-almonds',
    title: 'Apfel mit Mandeln',
    servings: 1,
    slots: ['snack'],
    timeMinutes: 1,
    difficulty: 'easy',
    equipment: [],
    cost: 'low',
    tags: ['schnell', 'vegan'],
    items: [item('Apfel', 'apple', 1, 'piece'), item('Mandeln', 'almonds', 20, 'g')],
    steps: ['Apfel in Schnitze schneiden, mit den Mandeln geniessen.'],
  },
];

/** Grundzutaten, die nie still vorausgesetzt werden — auch in eigenen Rezepten. */
const BASIC_FOODS = new Set(['salt', 'sugar', 'baking_powder', 'rapeseed_oil', 'olive_oil', 'butter']);

module.exports = { BASIC_FOODS, LIBRARY };
