import { dotArc, piece, round, tileRows, type KindGeometry } from '../shapes';

/** Der Knuddel: ein weicher Tropfen aus drei Reihen, unten drei kleine Fuesse, oben ein Glanz. */
export const blob: KindGeometry = {
  back: [
    ...[25, 43, 61].map((x, index) =>
      piece({
        id: `foot-${index}`,
        tone: 'bodyAlt',
        x,
        y: 76,
        width: 14,
        height: 9,
        corners: 4.5,
        wave: 0.34 + index * 0.02,
      }),
    ),
    ...tileRows(
      'jelly',
      [
        {
          x: 31,
          y: 22,
          width: 38,
          height: 17,
          count: 2,
          left: [16, 3, 3, 3],
          middle: round(3),
          right: [3, 16, 3, 3],
        },
        {
          x: 23,
          y: 41,
          width: 54,
          height: 18,
          count: 3,
          left: [10, 3, 3, 3],
          middle: round(3),
          right: [3, 10, 3, 3],
        },
        {
          x: 18,
          y: 61,
          width: 64,
          height: 16,
          count: 4,
          left: [3, 3, 3, 12],
          middle: [3, 3, 6, 6],
          right: [3, 3, 12, 3],
        },
      ],
      2,
    ),
  ],
  face: [
    piece({
      id: 'shine',
      layer: 'face',
      tone: 'shine',
      x: 34,
      y: 27,
      width: 9,
      height: 4.5,
      corners: 2.25,
      rotate: -25,
      wave: 0.64,
    }),
    piece({
      id: 'shine-dot',
      layer: 'face',
      tone: 'shine',
      x: 45,
      y: 25.5,
      width: 3,
      height: 3,
      corners: 1.5,
      wave: 0.68,
    }),
    piece({
      id: 'cheek-left',
      layer: 'face',
      tone: 'cheek',
      x: 26,
      y: 62,
      width: 8,
      height: 4.5,
      corners: 2.25,
      wave: 0.72,
    }),
    piece({
      id: 'cheek-right',
      layer: 'face',
      tone: 'cheek',
      x: 66,
      y: 62,
      width: 8,
      height: 4.5,
      corners: 2.25,
      wave: 0.74,
    }),
    ...dotArc({
      id: 'mouth',
      tone: 'ink',
      cx: 50,
      cy: 58.5,
      radius: 5,
      dot: 2.6,
      count: 5,
      from: 30,
      to: 150,
      wave: 0.62,
      spread: 0.2,
    }),
  ],
  eyes: {
    left: { x: 40, y: 49 },
    right: { x: 60, y: 49 },
    scale: 1.05,
    onPlate: false,
    wave: 0.56,
  },
  crown: { x: 50, y: 22 },
  bow: { x: 64, y: 25 },
};
