import { dotArc, piece, tileGrid, type KindGeometry } from '../shapes';

/** Schnurrhaare: je Seite zwei, die aussen leicht auseinandergehen. */
const WHISKERS = [
  { id: 'whisker-left-top', x: 21, y: 55.5, rotate: 8 },
  { id: 'whisker-left-low', x: 21, y: 60, rotate: -8 },
  { id: 'whisker-right-top', x: 67, y: 55.5, rotate: -8 },
  { id: 'whisker-right-low', x: 67, y: 60, rotate: 8 },
] as const;

/** Die Katze: ein breiter Kopf mit spitzen Ohren, Nase, Schnurrhaaren und einem Schwanz. */
export const cat: KindGeometry = {
  back: [
    piece({
      id: 'tail',
      tone: 'bodyAlt',
      x: 72,
      y: 64,
      width: 8,
      height: 26,
      corners: 4,
      rotate: 28,
      wave: 0.42,
    }),
    // Ein gedrehtes Quadrat, dessen Spitze nach oben zeigt; der Rest steckt hinter dem Kopf.
    piece({
      id: 'ear-left',
      tone: 'body',
      x: 21,
      y: 17,
      width: 20,
      height: 20,
      corners: [3, 7, 7, 7],
      rotate: 35,
      wave: 0.36,
    }),
    piece({
      id: 'ear-right',
      tone: 'body',
      x: 59,
      y: 17,
      width: 20,
      height: 20,
      corners: [3, 7, 7, 7],
      rotate: 55,
      wave: 0.38,
    }),
    piece({
      id: 'ear-inner-left',
      tone: 'cheek',
      x: 26,
      y: 23,
      width: 10,
      height: 10,
      corners: [2, 4, 4, 4],
      rotate: 35,
      wave: 0.5,
    }),
    piece({
      id: 'ear-inner-right',
      tone: 'cheek',
      x: 64,
      y: 23,
      width: 10,
      height: 10,
      corners: [2, 4, 4, 4],
      rotate: 55,
      wave: 0.52,
    }),
    piece({
      id: 'shoulders',
      tone: 'bodyAlt',
      x: 28,
      y: 79,
      width: 44,
      height: 14,
      corners: [12, 12, 3, 3],
      wave: 0.24,
    }),
    ...tileGrid({
      id: 'tile',
      x: 20,
      y: 30,
      width: 60,
      height: 48,
      cols: 3,
      rows: 3,
      gap: 2,
      inner: 3,
      top: 14,
      bottom: 14,
    }),
  ],
  face: [
    piece({
      id: 'nose',
      layer: 'face',
      tone: 'ink',
      x: 47.5,
      y: 54,
      width: 5,
      height: 5,
      corners: [2.5, 2.5, 1, 2.5],
      rotate: 45,
      wave: 0.62,
    }),
    ...dotArc({
      id: 'mouth-left',
      tone: 'ink',
      cx: 47.6,
      cy: 59.5,
      radius: 2.6,
      dot: 1.7,
      count: 3,
      from: 20,
      to: 160,
      wave: 0.64,
      spread: 0.06,
    }),
    ...dotArc({
      id: 'mouth-right',
      tone: 'ink',
      cx: 52.4,
      cy: 59.5,
      radius: 2.6,
      dot: 1.7,
      count: 3,
      from: 20,
      to: 160,
      wave: 0.7,
      spread: 0.06,
    }),
    ...WHISKERS.map((whisker, index) =>
      piece({
        id: whisker.id,
        layer: 'face',
        tone: 'ink',
        x: whisker.x,
        y: whisker.y,
        width: 12,
        height: 1.3,
        corners: 0.65,
        rotate: whisker.rotate,
        wave: 0.76 + index * 0.03,
      }),
    ),
    piece({
      id: 'cheek-left',
      layer: 'face',
      tone: 'cheek',
      x: 27,
      y: 62,
      width: 7,
      height: 4,
      corners: 2,
      wave: 0.72,
    }),
    piece({
      id: 'cheek-right',
      layer: 'face',
      tone: 'cheek',
      x: 66,
      y: 62,
      width: 7,
      height: 4,
      corners: 2,
      wave: 0.74,
    }),
  ],
  eyes: {
    left: { x: 39, y: 47 },
    right: { x: 61, y: 47 },
    scale: 0.95,
    onPlate: false,
    wave: 0.56,
  },
  crown: { x: 50, y: 30 },
  bow: { x: 50, y: 81 },
};
