import { piece, tileGrid, type KindGeometry } from '../shapes';

/** Das Gespenst: oben rund, unten gewellt, die Arme zum „Buh“ erhoben, der Mund ein kleines O. */
export const ghost: KindGeometry = {
  back: [
    piece({
      id: 'arm-left',
      tone: 'bodyAlt',
      x: 14,
      y: 46,
      width: 12,
      height: 8,
      corners: 4,
      rotate: 24,
      wave: 0.4,
    }),
    piece({
      id: 'arm-right',
      tone: 'bodyAlt',
      x: 74,
      y: 46,
      width: 12,
      height: 8,
      corners: 4,
      rotate: -24,
      wave: 0.42,
    }),
    ...tileGrid({
      id: 'tile',
      x: 24,
      y: 22,
      width: 52,
      height: 56,
      cols: 3,
      rows: 3,
      gap: 2,
      inner: 3,
      top: 16,
      bottom: 3,
    }),
    // Der Saum: vier Rundungen nebeneinander.
    ...[24, 37, 50, 63].map((x, index) =>
      piece({
        id: `hem-${index}`,
        tone: index % 2 === 0 ? 'bodyAlt' : 'body',
        x,
        y: 72,
        width: 13,
        height: 11,
        corners: 5.5,
        wave: 0.3 + index * 0.02,
      }),
    ),
  ],
  face: [
    piece({
      id: 'cheek-left',
      layer: 'face',
      tone: 'cheek',
      x: 31,
      y: 53,
      width: 7,
      height: 4,
      corners: 2,
      wave: 0.72,
    }),
    piece({
      id: 'cheek-right',
      layer: 'face',
      tone: 'cheek',
      x: 62,
      y: 53,
      width: 7,
      height: 4,
      corners: 2,
      wave: 0.74,
    }),
    piece({
      id: 'mouth',
      layer: 'face',
      tone: 'ink',
      x: 47.5,
      y: 52,
      width: 5,
      height: 6.5,
      corners: 2.5,
      wave: 0.66,
    }),
  ],
  eyes: { left: { x: 41, y: 42 }, right: { x: 59, y: 42 }, scale: 1, onPlate: false, wave: 0.56 },
  crown: { x: 50, y: 22 },
  bow: { x: 63, y: 25 },
};
