import { disc, piece, tileGrid, type KindGeometry } from '../shapes';

/** Die Federn auf dem Bauch: fuenf Punkte in zwei Reihen. */
const BELLY = [
  { x: 42, y: 68 },
  { x: 50, y: 70.5 },
  { x: 58, y: 68 },
  { x: 46, y: 76 },
  { x: 54, y: 76 },
] as const;

/** Die Eule: ein Ei mit Federbuescheln, grossen Gesichtsscheiben, Schnabel und Fluegeln. */
export const owl: KindGeometry = {
  back: [
    piece({
      id: 'wing-left',
      tone: 'bodyAlt',
      x: 13,
      y: 46,
      width: 11,
      height: 30,
      corners: [10, 4, 6, 10],
      rotate: 10,
      wave: 0.38,
    }),
    piece({
      id: 'wing-right',
      tone: 'bodyAlt',
      x: 76,
      y: 46,
      width: 11,
      height: 30,
      corners: [4, 10, 10, 6],
      rotate: -10,
      wave: 0.4,
    }),
    piece({
      id: 'tuft-left',
      tone: 'body',
      x: 24,
      y: 14,
      width: 10,
      height: 18,
      corners: [5, 5, 2, 2],
      rotate: -24,
      wave: 0.44,
    }),
    piece({
      id: 'tuft-right',
      tone: 'body',
      x: 66,
      y: 14,
      width: 10,
      height: 18,
      corners: [5, 5, 2, 2],
      rotate: 24,
      wave: 0.46,
    }),
    ...tileGrid({
      id: 'tile',
      x: 22,
      y: 22,
      width: 56,
      height: 68,
      cols: 3,
      rows: 4,
      gap: 2,
      inner: 3,
      top: 18,
      bottom: 18,
    }),
    piece({
      id: 'foot-left',
      tone: 'beak',
      x: 39,
      y: 89,
      width: 8,
      height: 5,
      corners: 2.5,
      wave: 0.5,
    }),
    piece({
      id: 'foot-right',
      tone: 'beak',
      x: 53,
      y: 89,
      width: 8,
      height: 5,
      corners: 2.5,
      wave: 0.52,
    }),
  ],
  face: [
    disc('plate-left', 'plate', { x: 39, y: 44 }, 24, 0.46),
    disc('plate-right', 'plate', { x: 61, y: 44 }, 24, 0.48),
    piece({
      id: 'beak',
      layer: 'face',
      tone: 'beak',
      x: 46.5,
      y: 51.5,
      width: 7,
      height: 7,
      corners: [2, 2, 1, 2],
      rotate: 45,
      wave: 0.66,
    }),
    ...BELLY.map((spot, index) =>
      disc(`belly-${index}`, 'pattern', spot, 3.6, 0.76 + index * 0.03),
    ),
  ],
  eyes: { left: { x: 39, y: 44 }, right: { x: 61, y: 44 }, scale: 1.15, onPlate: true, wave: 0.56 },
  crown: { x: 50, y: 22 },
  bow: { x: 50, y: 64 },
};
