import { dotArc, piece, tileGrid, type KindGeometry } from '../shapes';

/** Der Roboter, mit dem alles anfing: ein Kopf aus 16 Kacheln, ein Schild davor, Ohren seitlich. */
export const robot: KindGeometry = {
  back: [
    ...tileGrid({
      id: 'tile',
      x: 18,
      y: 24,
      width: 64,
      height: 58,
      cols: 4,
      rows: 4,
      gap: 2,
      inner: 3.5,
      top: 9,
      bottom: 9,
    }),
    piece({
      id: 'body',
      tone: 'body',
      x: 24,
      y: 90,
      width: 52,
      height: 10,
      corners: [10, 10, 3, 3],
      wave: 0.24,
    }),
    piece({
      id: 'neck',
      tone: 'bodyAlt',
      x: 40,
      y: 84,
      width: 20,
      height: 5,
      corners: 2.5,
      wave: 0.32,
    }),
    piece({
      id: 'ear-left',
      tone: 'bodyAlt',
      x: 11,
      y: 44,
      width: 8,
      height: 18,
      corners: [4, 1.5, 1.5, 4],
      wave: 0.38,
    }),
    piece({
      id: 'ear-right',
      tone: 'bodyAlt',
      x: 81,
      y: 44,
      width: 8,
      height: 18,
      corners: [1.5, 4, 4, 1.5],
      wave: 0.4,
    }),
  ],
  face: [
    piece({
      id: 'visor',
      layer: 'face',
      tone: 'plate',
      x: 25,
      y: 35,
      width: 50,
      height: 34,
      corners: 13,
      wave: 0.46,
    }),
    piece({
      id: 'cheek-left',
      layer: 'face',
      tone: 'cheek',
      x: 28.5,
      y: 58,
      width: 7,
      height: 4,
      corners: 2,
      wave: 0.72,
    }),
    piece({
      id: 'cheek-right',
      layer: 'face',
      tone: 'cheek',
      x: 64.5,
      y: 58,
      width: 7,
      height: 4,
      corners: 2,
      wave: 0.74,
    }),
    ...dotArc({
      id: 'smile',
      tone: 'eye',
      cx: 50,
      cy: 56,
      radius: 8,
      dot: 3.2,
      count: 7,
      from: 25,
      to: 155,
      wave: 0.62,
      spread: 0.24,
    }),
  ],
  eyes: {
    left: { x: 39, y: 49.5 },
    right: { x: 61, y: 49.5 },
    scale: 1,
    onPlate: true,
    wave: 0.56,
  },
  crown: { x: 50, y: 24 },
  bow: { x: 50, y: 87 },
};
